CREATE TABLE network_node (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_type   VARCHAR(20)      NOT NULL,
    name        VARCHAR(255)     NOT NULL,
    latitude    DOUBLE PRECISION NOT NULL,
    longitude   DOUBLE PRECISION NOT NULL,
    status      VARCHAR(20)      NOT NULL,
    created_at  TIMESTAMP        NOT NULL
);

CREATE TABLE supplier (
    id                          BIGINT PRIMARY KEY REFERENCES network_node (id),
    reliability_rating          DOUBLE PRECISION NOT NULL,
    lead_time_capability_days   INT              NOT NULL
);

CREATE TABLE factory (
    id                   BIGINT PRIMARY KEY REFERENCES network_node (id),
    production_capacity  INT NOT NULL,
    current_output       INT NOT NULL
);

CREATE TABLE warehouse (
    id             BIGINT PRIMARY KEY REFERENCES network_node (id),
    capacity       INT NOT NULL,
    current_stock  INT NOT NULL
);

CREATE TABLE port (
    id                    BIGINT PRIMARY KEY REFERENCES network_node (id),
    throughput_capacity   INT         NOT NULL,
    operational_status    VARCHAR(20) NOT NULL
);

CREATE TABLE route (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_id        BIGINT         NOT NULL REFERENCES network_node (id),
    destination_id   BIGINT         NOT NULL REFERENCES network_node (id),
    cost             NUMERIC(12, 2) NOT NULL,
    lead_time_hours  INT            NOT NULL,
    capacity         INT            NOT NULL
);

CREATE TABLE shipment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id        BIGINT      NOT NULL REFERENCES route (id),
    origin_id       BIGINT      NOT NULL REFERENCES network_node (id),
    destination_id  BIGINT      NOT NULL REFERENCES network_node (id),
    status          VARCHAR(20) NOT NULL,
    quantity        INT         NOT NULL,
    eta             TIMESTAMP
);

CREATE TABLE app_user (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL,
    role           VARCHAR(20)  NOT NULL,
    active         BOOLEAN      NOT NULL
);
