CREATE TABLE disruption (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_node_id    BIGINT REFERENCES network_node (id),
    target_route_id   BIGINT REFERENCES route (id),
    severity          VARCHAR(20) NOT NULL,
    duration_hours    INT         NOT NULL,
    start_time        TIMESTAMP   NOT NULL,
    CONSTRAINT chk_disruption_exactly_one_target CHECK (
        (target_node_id IS NOT NULL AND target_route_id IS NULL)
        OR (target_node_id IS NULL AND target_route_id IS NOT NULL)
    )
);
